name: CI
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
jobs:
  test-single:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make with g++
        run: make -j 2 fugaku_benchmark= omp=1  compiler=gnu arch=skylake rdma= mpi= powerapi=
      - name: checking
        run: |
          ./main 32 6 4 3   1 1 1 1    -1   -1  6 50 > CASE0
          egrep ":  |2     ="  CASE0      | awk '{printf("%30s %30s\n", $1, $NF)}'> res1
          egrep ":  |2     ="  data/CASE0 | awk '{print $NF}'> res2
          paste res1 res2 |awk '{d=sqrt(($2-$3)^2);printf("%27s %22s %22s %e\n", $1, $2, $3, d)}' >res
  test-MPI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install openmpi
        run: sudo apt-get install openmpi-doc openmpi-bin libopenmpi-dev
      - name: make with mpic++(g++)
        run: make -j 2 fugaku_benchmark= omp=1  compiler=openmpi-gnu arch=skylake rdma= mpi=1 powerapi=
      - name: checking
        run: |
          mpirun -np 2 ./main 32 6 4 3   1 1 1 2    -1   -1  6 50 > CASE1
          egrep ":  |2     ="  CASE1      | awk '{printf("%30s %30s\n", $1, $NF)}'> res1
          egrep ":  |2     ="  data/CASE1 | awk '{print $NF}'> res2
          paste res1 res2 |awk '{d=sqrt(($2-$3)^2);printf("%27s %22s %22s %e\n", $1, $2, $3, d)}' >res
      # Runs a set of commands using the runners shell
      - name: show env
        run: |
          echo uname -a
          uname -a
          echo mpicc --version
          mpicc --version
          echo mpirun --version
          mpirun --version
