name: CI
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
jobs:
  test-single:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make with g++
        run: make -j 2 fugaku_benchmark= omp=1  compiler=gnu arch=skylake rdma= mpi= powerapi=
      - name: checking
        run: |
          ./main 32 6 4 3   1 1 1 1    -1   -1  6 50 > CASE0
	  ./check.sh CASE0 data/CASE0
  test-MPI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install openmpi
        run: sudo apt-get install openmpi-doc openmpi-bin libopenmpi-dev
      - name: make with mpic++(g++)
        run: make -j 2 fugaku_benchmark= omp=1  compiler=openmpi-gnu arch=skylake rdma= mpi=1 powerapi=
      - name: checking
        run: |
          mpirun -np 2 ./main 32 6 4 3   1 1 1 2    -1   -1  6 50 > CASE1
          ./check.sh CASE1 data/CASE1
      # Runs a set of commands using the runners shell
      - name: show env
        run: |
          echo uname -a
          uname -a
          echo mpicc --version
          mpicc --version
          echo mpirun --version
          mpirun --version
